app:
  version: 1.0.0
jwt:
  secret: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fbb114b92aa48bda8e7cc72f1c0e65e1}
  expiration: 900000 # 15 minutes
  refresh-token:
    expiration: 604800000 # 7 jours
server:
  port: 8383
  servlet:
    context-path: /gkfcsolution
spring:
  application:
    name: springboot_Project_structure
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/springboot_Project_structure?createDatabaseIfNotExist=true
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
  profiles:
    active: ${SPRING_PROFILE:dev}
  logging:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
